name: Android Apk - Build & Google Play Release

on:
  push:
    branches:
      - 'release*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Use Node.js 14.11.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.11.0

      - name: NPM Install, Build, (Test)
        run: |
          sh prepare_release.sh
          npm ci
          npm run android:build

      - name: Publish Apk to Github Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: android/app/build/outputs/apk/signed/release/app-signed-release.apk
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 'latest'
          title: 'BreakOut QA - apk'
          prerelease: false

      - name: Publish Android Bundle to Google Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_PLAIN_TEXT }}
          packageName: com.tradiumapp.breakout
          releaseFile: android/app/build/outputs/apk/signed/release/app-signed-release.apk
          track: production
          whatsNewDirectory: distribution/whatsnew
