name: Android Apk - Build & Release

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11

      - name: Use Node.js 14.11.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.11.0

      - name: NPM Install, Build, (Test)
        run: |
          sh prepare_qa.sh
          npm ci
          npm run android:build
          # npm run bundle

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-signed-release.apk
          path: android/app/build/outputs/apk/signed/release/app-signed-release.apk

      - name: Publish Apk to Github Release
        uses: marvinpinto/action-automatic-releases@latest
        if: github.ref == 'refs/heads/master'
        with:
          files: android/app/build/outputs/apk/signed/release/app-signed-release.apk
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          title: "BreakOut QA - apk"
          prerelease: false
